# parameters.yml

# parametros globais
global:
  # mude para a data de rodagem do seu projeto
  run_date:
    day: 14
    month: 9
    year: 2024
  user:
    # mude para o seu proprio diretorio
    project_path: "C:/Users/gufer/OneDrive/Documentos/FIAP/Fase_03/mtg-project"
  
# pipeline de preprocessamento de dados
preprocessing:
  webscraper:
    zip_url: "https://mtgjson.com/api/v5/AllDeckFiles.zip"
    zip_folder: "data/01_raw/"
    log_folder: "data/01_raw/decks_log/"
    deck_cards: 40
    sample_size_ratio: 0.1

# pipeline de simulacao
simulation:
  n_players: 4
  matches_per_player: 10
  hand_size_stop: 0
  max_turns: 12
  max_mulligans: 3
  mulligan_prob: 0.20
  extra_land_prob: 0.10
  log_folder: "data/02_intermediate/simulation_log/"

# Pipeline de modelagem
modeling:
  feature_engineering:
    feat_corr_threshold: 0.90
  feature_selection:
    n_test_players: None
    turn_threshold: 3
    target_column: "mana_curve_efficiency"
  
  
# Pipeline de avaliação
evaluation:
  # Parâmetros para avaliação do modelo
  metrics:
    accuracy_threshold: 0.85
    f1_threshold: 0.7
  # Parâmetros para relatórios
  reporting:
    save_reports: true
    report_format: "pdf"
