# parameters.yml

# parametros globais
global:
  user:
    # mude para o seu proprio diretorio
    project_path: "C:/Users/gufer/OneDrive/Documentos/FIAP/Fase_03/mtg-project"
  
# pipeline de preprocessamento de dados
preprocessing:
  webscraper:
    zip_url: "https://mtgjson.com/api/v5/AllDeckFiles.zip"
    zip_folder: "data/01_raw/"
    log_folder: "data/01_raw/decks_log/"
    deck_cards: 40
    sample_size_ratio: 0.25

# pipeline de simulacao
simulation:
  n_players: 4
  matches_per_player: 10
  hand_size_stop: 0
  max_turns: 12
  max_mulligans: 3
  mulligan_prob: 0.20
  extra_land_prob: 0.10
  log_folder: "data/02_intermediate/simulation_log/"

# Pipeline de modelagem
modeling:
  feature_engineering:
    feat_corr_threshold: 0.90
  feature_selection:
    hide_players: False
    n_test_players: None
    hide_advanced_turns: True
    turn_threshold: 5
    target_column: "mana_curve_efficiency"
  model_selection:
    params_grid:  
      max_depth: [3, 5, 10, 20, None]
      min_samples_split: [2, 10, 20]
      min_samples_leaf: [1, 5, 10]
      max_features: [None, 'sqrt', 'log2']
      max_leaf_nodes: [None, 10, 20, 50]
      min_weight_fraction_leaf: [0.0, 0.1, 0.2]
    scoring_metric: "f1"

reporting:
  initial_turn_plot: 10
  final_turn_plot: 100